from __future__ import annotations

import os
import subprocess
from pathlib import Path


CACHE_DIR = Path.home() / ".cache" / "zibi"
LAST_OUTPUT_PATH = CACHE_DIR / "last_output.txt"


def ensure_cache() -> None:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    LAST_OUTPUT_PATH.touch(exist_ok=True)


def hook_script(shell: str = "auto") -> str:
    shell = detect_shell() if shell == "auto" else shell
    if shell == "fish":
        return fish_hook_script()
    return sh_hook_script()


def detect_shell() -> str:
    env_shell = Path(os.environ.get("SHELL", "")).name.lower()
    if env_shell in {"fish", "bash", "zsh"}:
        return env_shell

    try:
        parent = subprocess.run(
            ["ps", "-p", str(os.getppid()), "-o", "comm="],
            check=False,
            capture_output=True,
            text=True,
            timeout=2,
        ).stdout.strip()
    except Exception:
        parent = ""

    parent_shell = Path(parent).name.lower().lstrip("-")
    if parent_shell in {"fish", "bash", "zsh"}:
        return parent_shell
    return "bash"


def sh_hook_script() -> str:
    path = str(LAST_OUTPUT_PATH)
    cache = str(CACHE_DIR)
    return f"""# zibi shell integration for bash and zsh
# Generated by: zibi --init
#
# This provides a reliable capture wrapper:
#   zibi_run <command> [args...]
#   run <command> [args...]
#
# Example:
#   zibi_run pytest -q
#   zibi --snatch
#
# Fully transparent capture of every shell command is not reliable in portable
# shell code. zibi therefore ships an explicit tee wrapper that works in bash,
# zsh, and fish without changing command semantics unexpectedly.

export ZIBI_LAST_OUTPUT="{path}"
mkdir -p "{cache}"
: > "$ZIBI_LAST_OUTPUT"

zibi_run() {{
  mkdir -p "{cache}"
  "$@" 2>&1 | tee "$ZIBI_LAST_OUTPUT"
  if [ -n "${{ZSH_VERSION:-}}" ]; then
    return $pipestatus[1]
  fi
  return ${{PIPESTATUS[0]}}
}}

run() {{
  zibi_run "$@"
}}

zibi_alias_common() {{
  alias pytest='zibi_run pytest'
  alias python='zibi_run python'
  alias python3='zibi_run python3'
  alias node='zibi_run node'
  alias npm='zibi_run npm'
  alias git='zibi_run git'
  alias cargo='zibi_run cargo'
  alias go='zibi_run go'
}}

if [ -n "${{ZSH_VERSION:-}}" ]; then
  autoload -Uz add-zsh-hook 2>/dev/null || true
  zibi_preexec() {{ export ZIBI_LAST_COMMAND="$1"; }}
  zibi_precmd() {{ :; }}
  add-zsh-hook preexec zibi_preexec 2>/dev/null || true
  add-zsh-hook precmd zibi_precmd 2>/dev/null || true
elif [ -n "${{BASH_VERSION:-}}" ]; then
  zibi_debug_hook() {{ export ZIBI_LAST_COMMAND="$BASH_COMMAND"; }}
  trap 'zibi_debug_hook' DEBUG
  if [ -n "${{PROMPT_COMMAND:-}}" ]; then
    PROMPT_COMMAND=":; $PROMPT_COMMAND"
  else
    PROMPT_COMMAND=":"
  fi
fi

"""


def fish_hook_script() -> str:
    path = str(LAST_OUTPUT_PATH)
    cache = str(CACHE_DIR)
    return f"""# zibi shell integration for fish
# Generated by: zibi --init
#
# Install with:
#   zibi --init | source
# Persist with:
#   zibi --init > ~/.config/fish/conf.d/zibi.fish
#
# Usage:
#   zibi_run pytest -q
#   zibi --snatch

set -gx ZIBI_LAST_OUTPUT "{path}"
mkdir -p "{cache}"
printf "" > "$ZIBI_LAST_OUTPUT"

function zibi_run
    mkdir -p "{cache}"
    $argv 2>&1 | tee "$ZIBI_LAST_OUTPUT"
    return $pipestatus[1]
end

function run
    zibi_run $argv
end

function zibi_alias_common
    alias pytest='zibi_run pytest'
    alias python='zibi_run python'
    alias python3='zibi_run python3'
    alias node='zibi_run node'
    alias npm='zibi_run npm'
    alias git='zibi_run git'
    alias cargo='zibi_run cargo'
    alias go='zibi_run go'
end

"""
