from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path


CACHE_DIR = Path.home() / ".cache" / "zibi"
LAST_OUTPUT_PATH = CACHE_DIR / "last_output.txt"


def ensure_cache() -> None:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    LAST_OUTPUT_PATH.touch(exist_ok=True)


def get_shell_config_file(shell: str) -> Path:
    """Get the config file path for a given shell."""
    home = Path.home()
    if shell == "fish":
        config_dir = home / ".config" / "fish" / "conf.d"
        return config_dir / "zibi.fish"
    elif shell == "zsh":
        return home / ".zshrc"
    else:  # bash or default
        return home / ".bashrc"


def install_system_wide() -> tuple[bool, str]:
    """
    Install zibi as a system-wide command in /usr/local/bin or ~/.local/bin.
    
    This creates a wrapper script that can be called from anywhere.
    First tries /usr/local/bin, falls back to ~/.local/bin.
    Updates PATH in shell configs if needed.
    
    Returns:
        (success: bool, message: str)
    """
    # Determine installation directory
    install_dirs = [
        Path("/usr/local/bin"),
        Path("/usr/bin"),
    ]
    
    install_dir = None
    for directory in install_dirs:
        if directory.exists() and os.access(directory, os.W_OK):
            install_dir = directory
            break
    
    # If no writable system directory found, use ~/.local/bin
    if not install_dir:
        local_bin = Path.home() / ".local" / "bin"
        try:
            local_bin.mkdir(parents=True, exist_ok=True)
            if os.access(local_bin, os.W_OK):
                install_dir = local_bin
                needs_path_update = True
            else:
                return False, f"Permission denied: {local_bin}"
        except Exception as e:
            return False, f"Could not create {local_bin}: {e}"
    else:
        needs_path_update = False
    
    if not install_dir:
        return False, (
            "Cannot install system-wide. No writable directory found.\n"
            "Please ensure /usr/local/bin exists or run with sudo."
        )
    
    # Create wrapper script
    zibi_script = install_dir / "zibi"
    
    # Get the path to the current Python executable
    python_exe = sys.executable
    
    # Create the wrapper script
    wrapper_content = f"""#!/bin/sh
# zibi - Clipboard manager wrapper
# Auto-generated by: zibi --init
# This script runs the zibi Python module from any location

exec {python_exe} -m zibi.main "$@"
"""
    
    try:
        # Write the script
        zibi_script.write_text(wrapper_content, encoding="utf-8")
        
        # Make it executable
        zibi_script.chmod(0o755)
        
        # Verify installation
        if not zibi_script.exists():
            return False, f"Failed to write {zibi_script}"
        
        message = f"✓ zibi installed to {zibi_script}"
        
        # If using ~/.local/bin, ensure it's in PATH
        if needs_path_update:
            path_update_msg = _add_local_bin_to_path()
            message += f"\n{path_update_msg}"
        
        return True, message
    
    except PermissionError:
        return False, (
            f"Permission denied writing to {install_dir}.\n"
            "Try: sudo zibi --init"
        )
    except Exception as e:
        return False, f"Installation failed: {e}"


def uninstall_system_wide() -> tuple[bool, str]:
    """
    Remove zibi from system-wide installation.
    
    Returns:
        (success: bool, message: str)
    """
    uninstall_dirs = [
        Path("/usr/local/bin"),
        Path("/usr/bin"),
        Path.home() / ".local" / "bin",
    ]
    
    found = False
    removed = False
    errors = []
    
    for directory in uninstall_dirs:
        zibi_script = directory / "zibi"
        if zibi_script.exists():
            found = True
            try:
                zibi_script.unlink()
                removed = True
            except PermissionError:
                errors.append(f"Permission denied removing {zibi_script}. Try: sudo zibi --uninstall")
            except Exception as e:
                errors.append(str(e))
    
    if removed:
        message = "✓ zibi system-wide installation removed"
        if errors:
            message += f"\n⚠ Warnings: {'; '.join(errors)}"
        return True, message
    elif found:
        return False, f"Could not remove zibi. {'; '.join(errors) if errors else 'Permission denied'}"
    else:
        return False, "zibi not found in system paths (/usr/local/bin, /usr/bin, ~/.local/bin)"


def uninstall_shell_hooks(shell: str = "auto") -> tuple[bool, str]:
    """
    Remove zibi shell hooks from shell config files.
    
    Returns:
        (success: bool, message: str)
    """
    if shell == "auto":
        shell = detect_shell()
    
    shells_to_uninstall = [shell] if shell != "auto" else ["bash", "zsh"]
    success_count = 0
    errors = []
    
    # Bash
    if "bash" in shells_to_uninstall:
        bashrc = Path.home() / ".bashrc"
        if bashrc.exists():
            try:
                content = bashrc.read_text(encoding="utf-8")
                # Remove ZIBI markers and content
                lines = content.split("\n")
                new_lines = []
                in_zibi_block = False
                for line in lines:
                    if "=== ZIBI START ===" in line:
                        in_zibi_block = True
                        continue
                    elif "=== ZIBI END ===" in line:
                        in_zibi_block = False
                        continue
                    elif in_zibi_block:
                        continue
                    else:
                        new_lines.append(line)
                
                new_content = "\n".join(new_lines)
                bashrc.write_text(new_content, encoding="utf-8")
                success_count += 1
            except Exception as e:
                errors.append(f"bash: {e}")
    
    # Zsh
    if "zsh" in shells_to_uninstall:
        zshrc = Path.home() / ".zshrc"
        if zshrc.exists():
            try:
                content = zshrc.read_text(encoding="utf-8")
                lines = content.split("\n")
                new_lines = []
                in_zibi_block = False
                for line in lines:
                    if "=== ZIBI START ===" in line:
                        in_zibi_block = True
                        continue
                    elif "=== ZIBI END ===" in line:
                        in_zibi_block = False
                        continue
                    elif in_zibi_block:
                        continue
                    else:
                        new_lines.append(line)
                
                new_content = "\n".join(new_lines)
                zshrc.write_text(new_content, encoding="utf-8")
                success_count += 1
            except Exception as e:
                errors.append(f"zsh: {e}")
    
    # Fish
    if "fish" in shells_to_uninstall:
        fish_conf = Path.home() / ".config" / "fish" / "conf.d" / "zibi.fish"
        if fish_conf.exists():
            try:
                fish_conf.unlink()
                success_count += 1
            except Exception as e:
                errors.append(f"fish: {e}")
    
    if success_count > 0:
        message = f"✓ Removed zibi shell hooks from {success_count} shell(s)"
        if errors:
            message += f"\n⚠ Errors in: {'; '.join(errors)}"
        return True, message
    elif errors:
        return False, f"Failed to remove hooks: {'; '.join(errors)}"
    else:
        return True, "✓ No zibi shell hooks found to remove"


def verify_installation() -> tuple[bool, str]:
    """
    Verify that zibi is accessible from PATH.
    
    Returns:
        (is_accessible: bool, message: str)
    """
    try:
        # Try to run zibi --help to verify it works
        result = subprocess.run(
            ["zibi", "--help"],
            capture_output=True,
            timeout=5,
        )
        if result.returncode == 0:
            return True, "✓ zibi is accessible from PATH"
        else:
            return False, "✗ zibi command found but failed to run"
    except FileNotFoundError:
        return False, "✗ zibi not found in PATH. Restart terminal or run: exec bash"
    except subprocess.TimeoutExpired:
        return False, "✗ zibi command timed out"
    except Exception as e:
        return False, f"✗ Error verifying installation: {e}"


def _add_local_bin_to_path() -> str:
    """
    Add ~/.local/bin to PATH in all shell config files if not already present.
    
    Returns:
        Message describing what was done.
    """
    local_bin = Path.home() / ".local" / "bin"
    path_export = f'export PATH="$HOME/.local/bin:$PATH"'
    shells_updated = []
    
    # Bash
    bashrc = Path.home() / ".bashrc"
    if bashrc.exists():
        content = bashrc.read_text(encoding="utf-8")
        if ".local/bin" not in content:
            content += f"\n# Added by zibi --init\n{path_export}\n"
            bashrc.write_text(content, encoding="utf-8")
            shells_updated.append("bash")
    
    # Zsh
    zshrc = Path.home() / ".zshrc"
    if zshrc.exists():
        content = zshrc.read_text(encoding="utf-8")
        if ".local/bin" not in content:
            content += f"\n# Added by zibi --init\n{path_export}\n"
            zshrc.write_text(content, encoding="utf-8")
            shells_updated.append("zsh")
    
    if shells_updated:
        return f"✓ Added ~/.local/bin to PATH in: {', '.join(shells_updated)}"
    else:
        return f"✓ ~/.local/bin already in PATH"



def install_to_shell(shell: str = "auto") -> tuple[bool, str]:
    """
    Install zibi hooks to the shell config file.
    
    Returns:
        (success: bool, message: str)
    """
    shell = detect_shell() if shell == "auto" else shell
    
    if shell not in {"bash", "zsh", "fish"}:
        return False, f"Unsupported shell: {shell}"
    
    config_file = get_shell_config_file(shell)
    script = hook_script(shell)
    marker_start = "# === ZIBI START ==="
    marker_end = "# === ZIBI END ==="
    
    # Ensure parent directory exists
    config_file.parent.mkdir(parents=True, exist_ok=True)
    
    # Read existing config (if it exists)
    existing_content = ""
    if config_file.exists():
        existing_content = config_file.read_text(encoding="utf-8")
    
    # Check if already installed
    if marker_start in existing_content:
        # Remove old installation first
        start_idx = existing_content.find(marker_start)
        end_idx = existing_content.find(marker_end)
        if end_idx != -1:
            existing_content = (
                existing_content[:start_idx] + 
                existing_content[end_idx + len(marker_end):]
            ).lstrip("\n")
    
    # Add new installation with markers
    new_script = f"\n{marker_start}\n{script}{marker_end}\n"
    new_content = existing_content + new_script
    
    # Write back to config file
    config_file.write_text(new_content, encoding="utf-8")
    
    return True, f"✓ zibi installed to {config_file}"


def hook_script(shell: str = "auto") -> str:
    shell = detect_shell() if shell == "auto" else shell
    if shell == "fish":
        return fish_hook_script()
    return sh_hook_script()


def detect_shell() -> str:
    env_shell = Path(os.environ.get("SHELL", "")).name.lower()
    if env_shell in {"fish", "bash", "zsh"}:
        return env_shell

    try:
        parent = subprocess.run(
            ["ps", "-p", str(os.getppid()), "-o", "comm="],
            check=False,
            capture_output=True,
            text=True,
            timeout=2,
        ).stdout.strip()
    except Exception:
        parent = ""

    parent_shell = Path(parent).name.lower().lstrip("-")
    if parent_shell in {"fish", "bash", "zsh"}:
        return parent_shell
    return "bash"


def sh_hook_script() -> str:
    path = str(LAST_OUTPUT_PATH)
    cache = str(CACHE_DIR)
    return f"""# zibi shell integration for bash and zsh
# Generated by: zibi --init
#
# This provides a reliable capture wrapper:
#   zibi_run <command> [args...]
#   run <command> [args...]
#
# Example:
#   zibi_run pytest -q
#   zibi --snatch
#
# Fully transparent capture of every shell command is not reliable in portable
# shell code. zibi therefore ships an explicit tee wrapper that works in bash,
# zsh, and fish without changing command semantics unexpectedly.

export ZIBI_LAST_OUTPUT="{path}"
mkdir -p "{cache}"
: > "$ZIBI_LAST_OUTPUT"

zibi_run() {{
  mkdir -p "{cache}"
  "$@" 2>&1 | tee "$ZIBI_LAST_OUTPUT"
  if [ -n "${{ZSH_VERSION:-}}" ]; then
    return $pipestatus[1]
  fi
  return ${{PIPESTATUS[0]}}
}}

run() {{
  zibi_run "$@"
}}

zibi_alias_common() {{
  alias pytest='zibi_run pytest'
  alias python='zibi_run python'
  alias python3='zibi_run python3'
  alias node='zibi_run node'
  alias npm='zibi_run npm'
  alias git='zibi_run git'
  alias cargo='zibi_run cargo'
  alias go='zibi_run go'
}}

if [ -n "${{ZSH_VERSION:-}}" ]; then
  autoload -Uz add-zsh-hook 2>/dev/null || true
  zibi_preexec() {{ export ZIBI_LAST_COMMAND="$1"; }}
  zibi_precmd() {{ :; }}
  add-zsh-hook preexec zibi_preexec 2>/dev/null || true
  add-zsh-hook precmd zibi_precmd 2>/dev/null || true
elif [ -n "${{BASH_VERSION:-}}" ]; then
  zibi_debug_hook() {{ export ZIBI_LAST_COMMAND="$BASH_COMMAND"; }}
  trap 'zibi_debug_hook' DEBUG
  if [ -n "${{PROMPT_COMMAND:-}}" ]; then
    PROMPT_COMMAND=":; $PROMPT_COMMAND"
  else
    PROMPT_COMMAND=":"
  fi
fi

"""


def fish_hook_script() -> str:
    path = str(LAST_OUTPUT_PATH)
    cache = str(CACHE_DIR)
    return f"""# zibi shell integration for fish
# Generated by: zibi --init
#
# Install with:
#   zibi --init | source
# Persist with:
#   zibi --init > ~/.config/fish/conf.d/zibi.fish
#
# Usage:
#   zibi_run pytest -q
#   zibi --snatch

set -gx ZIBI_LAST_OUTPUT "{path}"
mkdir -p "{cache}"
printf "" > "$ZIBI_LAST_OUTPUT"

function zibi_run
    mkdir -p "{cache}"
    $argv 2>&1 | tee "$ZIBI_LAST_OUTPUT"
    return $pipestatus[1]
end

function run
    zibi_run $argv
end

function zibi_alias_common
    alias pytest='zibi_run pytest'
    alias python='zibi_run python'
    alias python3='zibi_run python3'
    alias node='zibi_run node'
    alias npm='zibi_run npm'
    alias git='zibi_run git'
    alias cargo='zibi_run cargo'
    alias go='zibi_run go'
end

"""
